"""
EvidenceBuilder — Generates a structured Markdown evidence report
after a successful pipeline run.

Returns: (markdown_str: str, filename: str)

Called by Orchestrator after BranchPRAgent succeeds.
The generated file is then attached to the Jira issue.
"""
from datetime import datetime, timezone
import logging

logger = logging.getLogger(__name__)


class EvidenceBuilder:

    @staticmethod
    def build(
        story,
        workflow_id: int,
        pr_output: dict,
        developer_output: dict,
        loop_count: int = 1,
        guardrail_count: int = 0,
    ) -> tuple[str, str]:
        """
        Build an evidence Markdown report.

        Args:
            story:            Story ORM object or dict.
            workflow_id:      Workflow DB ID.
            pr_output:        Output dict from BranchPRAgent.
            developer_output: Output dict from DeveloperAgent (last successful run).
            loop_count:       Total dev↔validator iterations used.
            guardrail_count:  Number of guardrail events fired during this run.

        Returns:
            (markdown_str, filename)  e.g. ("# DEVAA...", "evidence_SCRUM-42_wf12.md")
        """
        # ── Extract story fields ──────────────────────────────────
        if hasattr(story, 'title'):
            title               = story.title or ''
            jira_key            = getattr(story, 'jira_story_key', '') or ''
            description         = story.description or ''
            acceptance_criteria = story.acceptance_criteria or ''
            story_id            = story.id
        else:
            # dict fallback
            title               = story.get('title', '')
            jira_key            = story.get('jira_story_key', '')
            description         = story.get('description', '')
            acceptance_criteria = story.get('acceptance_criteria', '')
            story_id            = story.get('id', '')

        # ── Extract PR fields ─────────────────────────────────────
        pr_url      = pr_output.get('pr_url', 'N/A')
        pr_number   = pr_output.get('pr_number', '')
        branch_name = pr_output.get('branch_name', 'N/A')
        pr_summary  = pr_output.get('pr_summary', '')

        # ── Extract changed files ─────────────────────────────────
        changes: list[dict] = developer_output.get('changes', [])
        dev_summary: str    = developer_output.get('summary', '')

        # ── Acceptance criteria coverage ──────────────────────────
        ac_lines = []
        if acceptance_criteria:
            for line in acceptance_criteria.strip().splitlines():
                line = line.strip()
                if line:
                    ac_lines.append(f"- [x] {line}")
        ac_section = "\n".join(ac_lines) if ac_lines else "_No acceptance criteria recorded._"

        # ── Changed files table ───────────────────────────────────
        if changes:
            files_rows = "\n".join([
                f"| `{c.get('file', 'unknown')}` "
                f"| {c.get('action', '').capitalize()} "
                f"| {c.get('description', '')} |"
                for c in changes
            ])
            files_section = (
                "| File | Action | Description |\n"
                "|------|--------|-------------|\n"
                f"{files_rows}"
            )
        else:
            files_section = "_No file changes recorded by Developer Agent._"

        # ── Timestamp ─────────────────────────────────────────────
        now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")

        # ── Compose markdown ──────────────────────────────────────
        header_key = f"{jira_key}" if jira_key else f"Story #{story_id}"

        md = f"""# DEVAA Evidence Report — {header_key}

> Auto-generated by DEVAA Pipeline · {now_utc} UTC

---

## Story Details

| Field | Value |
|-------|-------|
| **Jira Key** | {jira_key or '_N/A_'} |
| **Title** | {title} |
| **Workflow ID** | #{workflow_id} |
| **PR** | [{f'#{pr_number}' if pr_number else 'Link'}]({pr_url}) |
| **Branch** | `{branch_name}` |

---

## Description

{description or '_No description provided._'}

---

## Changed Files

{files_section}

---

## Developer Summary

{dev_summary or '_No summary provided._'}

---

## Acceptance Criteria Coverage

{ac_section}

---

## PR Summary

{pr_summary or '_No PR summary generated._'}

---

## Pipeline Statistics

| Metric | Value |
|--------|-------|
| Developer → Validator loop iterations | {loop_count} |
| Guardrail events triggered | {guardrail_count} |
| Completed At | {now_utc} UTC |

---

_This report was automatically generated and attached to [{header_key}]({pr_url}) by DEVAA._
"""

        # ── Generate safe filename ────────────────────────────────
        safe_key = (jira_key or f"story{story_id}").replace("/", "-").replace(" ", "_")
        filename = f"evidence_{safe_key}_wf{workflow_id}.md"

        logger.info(
            f"[EvidenceBuilder] Built evidence report: {filename} "
            f"({len(changes)} changed files, {loop_count} loops)"
        )
        return md.strip(), filename
