"""Add external_provider and external_task_id to Story

Revision ID: 2c1f4b3f14e1
Revises: 
Create Date: 2026-09-09 17:16:22.017308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c1f4b3f14e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('repositories')
    op.drop_table('jira_comments')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('permissions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('audit_logs_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('audit_logs_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('audit_logs_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('guardrail_events', schema=None) as batch_op:
        batch_op.alter_column('rail_type',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='input | dialog | retrieval | execution | output',
               existing_nullable=False)
        batch_op.alter_column('triggered_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('guardrail_events_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('guardrail_events_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.alter_column('pr_status',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='open | merged | rejected | closed',
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))
        batch_op.alter_column('merged_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('pull_requests_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pull_requests_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pull_requests_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pull_requests_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['merged_by'], ['id'])
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.alter_column('decision',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='approved | rejected',
               existing_nullable=False)
        batch_op.alter_column('is_rework',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='TRUE = QA rejection driving rework, FALSE = regular review',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('qa_reviews_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('qa_reviews_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('qa_reviews_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pull_requests', ['pr_id'], ['id'])
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_task_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('external_provider', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='TO-DO | IN-PROGRESS | QA-TESTING | DONE | INVALID',
               existing_nullable=True,
               existing_server_default=sa.text("'TO-DO'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['external_task_id'])
        batch_op.drop_constraint(batch_op.f('stories_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['assignee_id'], ['id'])

    with op.batch_alter_table('success_metrics', schema=None) as batch_op:
        batch_op.alter_column('metric_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='eligibility_accuracy | file_selection | criteria_coverage | rework_count | loop_iterations | guardrail_hits | pr_quality',
               existing_nullable=False)
        batch_op.alter_column('measured_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('success_metrics_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('success_metrics_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.alter_column('step_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               comment=None,
               existing_comment='Intake | RepoAnalysis | Developer | Validator | BranchPR | Comment | Rework',
               existing_nullable=False)
        batch_op.alter_column('agent_prompt',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='Pending | In Progress | Completed | Failed | Skipped',
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('workflow_steps_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflows', ['workflow_id'], ['id'])

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               comment=None,
               existing_comment='Planning | Running | Completed | Failed | Awaiting QA | Rework',
               existing_server_default=sa.text("'Planning'"))
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('workflows_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'stories', ['story_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workflows_ibfk_1'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment='Planning | Running | Completed | Failed | Awaiting QA | Rework',
               existing_server_default=sa.text("'Planning'"))

    with op.batch_alter_table('workflow_steps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('workflow_steps_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               comment='Pending | In Progress | Completed | Failed | Skipped',
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('agent_prompt',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('step_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               comment='Intake | RepoAnalysis | Developer | Validator | BranchPR | Comment | Rework',
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('success_metrics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('success_metrics_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('success_metrics_ibfk_2'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('measured_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('metric_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='eligibility_accuracy | file_selection | criteria_coverage | rework_count | loop_iterations | guardrail_hits | pr_quality',
               existing_nullable=False)

    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stories_ibfk_1'), 'users', ['assignee_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               comment='TO-DO | IN-PROGRESS | QA-TESTING | DONE | INVALID',
               existing_nullable=True,
               existing_server_default=sa.text("'TO-DO'"))
        batch_op.drop_column('external_provider')
        batch_op.drop_column('external_task_id')

    with op.batch_alter_table('qa_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('qa_reviews_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('qa_reviews_ibfk_3'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('qa_reviews_ibfk_2'), 'pull_requests', ['pr_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('is_rework',
               existing_type=mysql.TINYINT(display_width=1),
               comment='TRUE = QA rejection driving rework, FALSE = regular review',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('decision',
               existing_type=mysql.VARCHAR(length=50),
               comment='approved | rejected',
               existing_nullable=False)

    with op.batch_alter_table('pull_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pull_requests_ibfk_3'), 'users', ['created_by'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('pull_requests_ibfk_2'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('pull_requests_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('pull_requests_ibfk_4'), 'users', ['merged_by'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('merged_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('pr_status',
               existing_type=mysql.VARCHAR(length=50),
               comment='open | merged | rejected | closed',
               existing_nullable=True,
               existing_server_default=sa.text("'open'"))

    with op.batch_alter_table('guardrail_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('guardrail_events_ibfk_2'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('guardrail_events_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('triggered_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('rail_type',
               existing_type=mysql.VARCHAR(length=50),
               comment='input | dialog | retrieval | execution | output',
               existing_nullable=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_logs_ibfk_2'), 'stories', ['story_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('audit_logs_ibfk_1'), 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('audit_logs_ibfk_3'), 'users', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('jira_comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jira_story_key', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('comment_body', mysql.TEXT(), nullable=False),
    sa.Column('comment_type', mysql.VARCHAR(length=50), nullable=True, comment='validation_failure | ready_for_dev | pr_ready | rework_triggered'),
    sa.Column('jira_comment_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('posted_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('jira_comments_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('repositories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('story_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repository_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('repository_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('source_branch', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('commit_sha', mysql.VARCHAR(length=40), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('repositories_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('role_permissions_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('role_permissions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
