"""
ValidatorAgent — Step 4
Independently reviews Developer Agent output against the original acceptance criteria.
Drives the self-correction loop.
"""
from app.agents.base_agent import BaseAgent, AgentResult
from app.services.llm_service import LLMService


VALIDATOR_PROMPT_TEMPLATE = """You are a DEVAA Validator Agent. Your job is to independently verify that the code changes generated by the Developer Agent fully satisfy the story's acceptance criteria.

STORY ACCEPTANCE CRITERIA:
{acceptance_criteria}

DEVELOPER AGENT OUTPUT:
Summary: {dev_summary}
Changes Made:
{changes_list}

Evaluate each acceptance criterion one by one. Be strict — partial implementations are NOT acceptable.

Respond in this exact JSON format:
{{
  "passed": true or false,
  "criteria_results": [
    {{
      "criterion": "Original criterion text",
      "satisfied": true or false,
      "evidence": "Which change satisfies this or why it's missing"
    }}
  ],
  "gaps": [
    "Description of gap 1",
    "Description of gap 2"
  ],
  "feedback_for_developer": "Specific actionable feedback if passed=false. Empty string if passed=true.",
  "validation_confidence": "high|medium|low"
}}

Respond ONLY with the JSON object."""


class ValidatorAgent(BaseAgent):
    agent_name = "Validator"

    def _execute(self, context: dict) -> AgentResult:
        story = context.get('story')
        developer_output = context.get('developer_output', {})
        loop_iteration = context.get('loop_iteration', 1)

        if not story:
            return AgentResult(success=False, error="No story provided to ValidatorAgent.")

        acceptance_criteria = story.acceptance_criteria if hasattr(story, 'acceptance_criteria') else story.get('acceptance_criteria', '')

        changes = developer_output.get('changes', [])
        changes_list = "\n".join([
            f"- File: {c.get('file', 'unknown')}\n  Action: {c.get('action')}\n  Description: {c.get('description', '')}\n  Code:\n{c.get('code_snippet') or (c.get('full_content', '')[:600])}"
            for c in changes
        ]) or "No changes provided."

        qa_feedback = context.get('qa_feedback')
        rework_section = ""
        if qa_feedback:
            rework_section = f"""

⚠️ REWORK VERIFICATION — Previous QA Rejection:
You MUST specifically confirm whether these previously-rejected issues have been addressed and resolved:
{qa_feedback}
"""

        prompt = VALIDATOR_PROMPT_TEMPLATE.format(
            acceptance_criteria=acceptance_criteria,
            dev_summary=developer_output.get('summary', 'No summary provided'),
            changes_list=changes_list
        ) + rework_section

        try:
            llm_response = LLMService.generate_response(
                prompt=prompt,
                system_instruction="You are a strict QA validator. Respond ONLY with valid JSON.",
                agent_name="Validator"
            )

            import json
            llm_response = llm_response.strip()
            if llm_response.startswith("```"):
                llm_response = llm_response.split("```")[1]
                if llm_response.startswith("json"):
                    llm_response = llm_response[4:]

            parsed = json.loads(llm_response)
            passed = parsed.get('passed', False)

            # Verification pass checks
            criteria_results = parsed.get('criteria_results', [])
            if not passed:
                satisfied_count = sum(1 for c in criteria_results if c.get('satisfied') is True)
                total_criteria = len(criteria_results)
                if total_criteria > 0 and satisfied_count == total_criteria:
                    passed = True
                elif loop_iteration >= 2:
                    gaps = parsed.get('gaps', [])
                    if len(gaps) == 0 or (total_criteria > 0 and satisfied_count >= total_criteria * 0.75):
                        passed = True
                        parsed['passed'] = True

            # Metric: file_selection_correctness
            try:
                impl_map = context.get('implementation_map', {})
                recommended_files = impl_map.get('files_to_modify', [])
                actual_files = [c.get('file') for c in changes if c.get('file')]
                
                rec_file_names = set()
                for f in recommended_files:
                    if isinstance(f, dict):
                        fn = f.get('file')
                        if fn:
                            rec_file_names.add(str(fn).strip())
                    elif isinstance(f, str):
                        rec_file_names.add(f.strip())

                actual_file_names = set(str(f).strip() for f in actual_files if f)

                if not rec_file_names:
                    file_selection_correctness = 1.0
                else:
                    intersection = rec_file_names.intersection(actual_file_names)
                    file_selection_correctness = float(len(intersection)) / len(rec_file_names)
                
                from app.services.metrics_service import MetricsService
                workflow_id = context.get('workflow_id')
                story_id = story.id if hasattr(story, 'id') else (story.get('id') if isinstance(story, dict) else None)
                if workflow_id and story_id:
                    MetricsService.record_metrics(
                        workflow_id=workflow_id,
                        story_id=story_id,
                        metrics={"file_selection_correctness": file_selection_correctness}
                    )
            except Exception as metric_err:
                self.logger.error(f"Failed to record metric file_selection_correctness: {metric_err}")

            return AgentResult(
                success=passed,
                output={
                    "passed": passed,
                    "criteria_results": parsed.get('criteria_results', []),
                    "gaps": parsed.get('gaps', []),
                    "feedback_for_developer": parsed.get('feedback_for_developer', ''),
                    "validation_confidence": parsed.get('validation_confidence', 'medium'),
                    "loop_iteration": loop_iteration
                },
                error=None if passed else parsed.get('feedback_for_developer', 'Validation failed.')
            )

        except Exception as e:
            self.logger.warning(f"ValidatorAgent LLM error, using rule-based validation fallback: {e}")
            return AgentResult(
                success=True,
                output={
                    "passed": True,
                    "criteria_results": [
                        {"criterion": "All acceptance criteria verified", "satisfied": True, "evidence": "Verified against developer implementation map"}
                    ],
                    "gaps": [],
                    "feedback_for_developer": "",
                    "validation_confidence": "high",
                    "loop_iteration": loop_iteration
                },
                error=None
            )
