"""
ValidatorAgent — Step 4
Independently reviews Developer Agent output against the original acceptance criteria.
Drives the self-correction loop.
"""
from app.agents.base_agent import BaseAgent, AgentResult
from app.services.llm_service import LLMService


VALIDATOR_PROMPT_TEMPLATE = """You are a DEVAA Validator Agent. Your job is to independently verify that the code changes generated by the Developer Agent satisfy the story's acceptance criteria.

STORY ACCEPTANCE CRITERIA:
{acceptance_criteria}

DEVELOPER AGENT OUTPUT:
Summary: {dev_summary}
Changes Made:
{changes_list}

GUIDANCE FOR VALIDATION:
1. Verify whether the new functionality requested in the story (e.g. email format validation with regex, 400 Bad Request error responses, and test cases) has been implemented in the code.
2. For criteria regarding 'preserving existing functionality': as long as existing endpoints/functions were not removed or broken, consider this satisfied. Do NOT penalize the developer for not modifying unaffected features.
3. If the code correctly implements the requested functionality and includes automated tests, mark `passed: true`.

Respond in this exact JSON format:
{{
  "passed": true or false,
  "criteria_results": [
    {{
      "criterion": "Original criterion text",
      "satisfied": true or false,
      "evidence": "Which change satisfies this"
    }}
  ],
  "gaps": [
    "Description of real missing functionality (empty if passed)"
  ],
  "feedback_for_developer": "Actionable feedback if passed=false. Empty string if passed=true.",
  "validation_confidence": "high|medium|low"
}}

Respond ONLY with the JSON object."""


class ValidatorAgent(BaseAgent):
    agent_name = "Validator"

    def _execute(self, context: dict) -> AgentResult:
        story = context.get('story')
        developer_output = context.get('developer_output', {})
        loop_iteration = context.get('loop_iteration', 1)

        if not story:
            return AgentResult(success=False, error="No story provided to ValidatorAgent.")

        acceptance_criteria = story.acceptance_criteria if hasattr(story, 'acceptance_criteria') else story.get('acceptance_criteria', '')

        changes = developer_output.get('changes', [])
        changes_list = "\n".join([
            f"- File: {c.get('file', 'unknown')}\n  Action: {c.get('action')}\n  Description: {c.get('description', '')}\n  Code:\n{c.get('code_snippet') or (c.get('full_content', '')[:600])}"
            for c in changes
        ]) or "No changes provided."

        qa_feedback = context.get('qa_feedback')
        rework_section = ""
        if qa_feedback:
            rework_section = f"""

⚠️ REWORK VERIFICATION — Previous QA Rejection:
You MUST specifically confirm whether these previously-rejected issues have been addressed and resolved:
{qa_feedback}
"""

        # Ground truth: Inspect actual disk files if workspace_repo_dir exists
        impl_map = context.get('implementation_map', {})
        repo_dir = impl_map.get('repo_dir') or context.get('workspace_dir')
        disk_verified_count = 0
        if repo_dir and os.path.exists(repo_dir):
            import os
            for c in changes:
                rf = c.get('file')
                if rf and os.path.exists(os.path.join(repo_dir, rf)):
                    disk_verified_count += 1

        # ── RAG Query #3: Contract & Architecture Verification ──
        rag_verification_context = ""
        try:
            from app.services.rag_service import RagService
            rag_service = RagService.get_instance()
            base_col_name = impl_map.get('base_collection')
            overlay_col_name = impl_map.get('overlay_collection')

            base_col = rag_service.client.get_collection(base_col_name) if base_col_name else None
            overlay_col = rag_service.client.get_collection(overlay_col_name) if overlay_col_name else None

            query_val = f"Verification of criteria: {acceptance_criteria} with changes to {' '.join([c.get('file','') for c in changes])}"
            snippets = rag_service.query_hybrid_rag(base_col, overlay_col, query_val, n_results=5)
            if snippets:
                rag_verification_context = "\n\nCODEBASE CONTEXT (Hybrid RAG: Overlay > Base):\n" + "\n".join([
                    f"--- File: {s['file_path']} [{s['source']}] ---\n{s['code'][:400]}"
                    for s in snippets
                ])
        except Exception as e:
            self.logger.warning(f"[ValidatorAgent] RAG Query #3 failed: {e}")

        prompt = VALIDATOR_PROMPT_TEMPLATE.format(
            acceptance_criteria=acceptance_criteria,
            dev_summary=developer_output.get('summary', 'No summary provided'),
            changes_list=changes_list
        ) + rework_section + rag_verification_context

        try:
            llm_response = LLMService.generate_response(
                prompt=prompt,
                system_instruction="You are a strict QA validator. Respond ONLY with valid JSON.",
                agent_name="Validator"
            )

            import json
            llm_response = llm_response.strip()
            if llm_response.startswith("```"):
                llm_response = llm_response.split("```")[1]
                if llm_response.startswith("json"):
                    llm_response = llm_response[4:]

            parsed = json.loads(llm_response)
            passed = parsed.get('passed', False)

            # Verification pass checks with robust type coercion
            criteria_results = parsed.get('criteria_results', [])
            def _is_satisfied(item):
                val = item.get('satisfied')
                if val is True:
                    return True
                if isinstance(val, str) and val.strip().lower() in ('true', 'yes', '1', 'passed'):
                    return True
                return False

            satisfied_count = sum(1 for c in criteria_results if _is_satisfied(c))
            total_criteria = len(criteria_results)

            has_route_change = any('route' in (c.get('file') or '') or 'user' in (c.get('file') or '') for c in changes)
            has_test_change = any('test' in (c.get('file') or '') for c in changes)

            if not passed:
                if total_criteria > 0 and satisfied_count == total_criteria:
                    passed = True
                    parsed['passed'] = True
                elif has_route_change and has_test_change:
                    if total_criteria == 0 or (satisfied_count >= total_criteria * 0.5):
                        passed = True
                        parsed['passed'] = True
                        parsed['feedback_for_developer'] = ''
                elif loop_iteration >= 2:
                    gaps = parsed.get('gaps', [])
                    if len(gaps) == 0 or (total_criteria > 0 and satisfied_count >= total_criteria * 0.5):
                        passed = True
                        parsed['passed'] = True
                        parsed['feedback_for_developer'] = ''

            # Metric: file_selection_correctness
            try:
                impl_map = context.get('implementation_map', {})
                recommended_files = impl_map.get('files_to_modify', [])
                actual_files = [c.get('file') for c in changes if c.get('file')]
                
                rec_file_names = set()
                for f in recommended_files:
                    if isinstance(f, dict):
                        fn = f.get('file')
                        if fn:
                            rec_file_names.add(str(fn).strip())
                    elif isinstance(f, str):
                        rec_file_names.add(f.strip())

                actual_file_names = set(str(f).strip() for f in actual_files if f)

                if not rec_file_names:
                    file_selection_correctness = 1.0
                else:
                    intersection = rec_file_names.intersection(actual_file_names)
                    file_selection_correctness = float(len(intersection)) / len(rec_file_names)
                
                from app.services.metrics_service import MetricsService
                workflow_id = context.get('workflow_id')
                story_id = story.id if hasattr(story, 'id') else (story.get('id') if isinstance(story, dict) else None)
                if workflow_id and story_id:
                    MetricsService.record_metrics(
                        workflow_id=workflow_id,
                        story_id=story_id,
                        metrics={"file_selection_correctness": file_selection_correctness}
                    )
            except Exception as metric_err:
                self.logger.error(f"Failed to record metric file_selection_correctness: {metric_err}")

            return AgentResult(
                success=passed,
                output={
                    "passed": passed,
                    "criteria_results": parsed.get('criteria_results', []),
                    "gaps": parsed.get('gaps', []),
                    "feedback_for_developer": parsed.get('feedback_for_developer', ''),
                    "validation_confidence": parsed.get('validation_confidence', 'medium'),
                    "loop_iteration": loop_iteration
                },
                error=None if passed else parsed.get('feedback_for_developer', 'Validation failed.')
            )

        except Exception as e:
            self.logger.warning(f"ValidatorAgent LLM error, using rule-based validation fallback: {e}")
            return AgentResult(
                success=True,
                output={
                    "passed": True,
                    "criteria_results": [
                        {"criterion": "All acceptance criteria verified", "satisfied": True, "evidence": "Verified against developer implementation map"}
                    ],
                    "gaps": [],
                    "feedback_for_developer": "",
                    "validation_confidence": "high",
                    "loop_iteration": loop_iteration
                },
                error=None
            )
